kind: Deployment
apiVersion: apps/v1
metadata:
  name: pdf-gpt
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: pdf-gpt
  template:
    metadata:
      labels:
        app: pdf-gpt
    spec:
      containers:
        - name: pdf-gpt
          image: joeuzo/pdf-gpt:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: pdf-gpt-secrets
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: tmp-volume
          persistentVolumeClaim:
            claimName: pdf-gpt-pvc
