apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-gpt-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
