kind: Service
apiVersion: v1
metadata:
  name: pdf-gpt-service
  namespace: app
spec:
  selector:
    app: pdf-gpt
  type: ClusterIP
  # sessionAffinity: ClientIP
  ports:
    - port: 5000
      targetPort: 5000
