name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     # Using working-directory so Docker sees Dockerfile & requirements.txt
  #     - name: Build Docker Image (Test)
  #       working-directory: pdf-gpt/
  #       run: |
  #         docker build \
  #           -f Dockerfile \
  #           -t joeuzo/pdf-gpt:test-$(echo ${{ github.sha }} | cut -c1-7) \
  #           .


  push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Tag Docker Image
        working-directory: pdf-gpt/
        run: |
          docker build \
            -f Dockerfile \
            -t joeuzo/pdf-gpt:$(echo ${{ github.sha }} | cut -c1-7) \
            -t joeuzo/pdf-gpt:latest \
            .

      - name: Docker Hub login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push joeuzo/pdf-gpt:$(echo ${{ github.sha }} | cut -c1-7)
          docker push joeuzo/pdf-gpt:latest
